// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDhpC_erYDz2cDJpcD1O5a51vzGF-u2Y',
    appId: '1:464226347743:web:7ff7a553ea320eb740976a',
    messagingSenderId: '464226347743',
    projectId: 'smart-civic-connect-106ed',
    authDomain: 'smart-civic-connect-106ed.firebaseapp.com',
    storageBucket: 'smart-civic-connect-106ed.firebasestorage.app',
    measurementId: 'G-493R5ZE633',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFv8v1srDEPA8VQpl8YncIeCgg9daPE4',
    appId: '1:464226347743:android:2a260b2df485ab8c40976a',
    messagingSenderId: '464226347743',
    projectId: 'smart-civic-connect-106ed',
    storageBucket: 'smart-civic-connect-106ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGXj6KIHAk_BQMrQ0O4JyZdag8UT0574',
    appId: '1:464226347743:ios:f2df3b25ffe36d8140976a',
    messagingSenderId: '464226347743',
    projectId: 'smart-civic-connect-106ed',
    storageBucket: 'smart-civic-connect-106ed.firebasestorage.app',
    iosBundleId: 'com.example.smartCivicAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYGXj6KIHAk_BQMrQ0O4JyZdag8UT0574',
    appId: '1:464226347743:ios:f2df3b25ffe36d8140976a',
    messagingSenderId: '464226347743',
    projectId: 'smart-civic-connect-106ed',
    storageBucket: 'smart-civic-connect-106ed.firebasestorage.app',
    iosBundleId: 'com.example.smartCivicAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbDhpC_erYDz2cDJpcD1O5a51vzGF-u2Y',
    appId: '1:464226347743:web:ae00bd2cd45a2b2a40976a',
    messagingSenderId: '464226347743',
    projectId: 'smart-civic-connect-106ed',
    authDomain: 'smart-civic-connect-106ed.firebaseapp.com',
    storageBucket: 'smart-civic-connect-106ed.firebasestorage.app',
    measurementId: 'G-G2EZGRSFYT',
  );
}
